"""ai-config — Cross-AI tool configuration manager.

usage() is the --help text; cli_dispatch parses the arguments and runs the
command, and the implementations live in the commands/ subpackage.
"""

import sys

from . import cli_dispatch
from .console import BOLD, NC
from .paths import ENTRYPOINT


def usage() -> None:
    print(f"{BOLD}{ENTRYPOINT}{NC} — Cross-AI tool configuration manager")
    print()
    print(f"{BOLD}Usage:{NC}")
    print(f"  {ENTRYPOINT} <command> [tool] [--force]")
    print()
    print(f"{BOLD}Global options:{NC}")
    print("  --force, -f     Answer every [y/N] confirmation with yes, so a")
    print("                  script or agent with no terminal runs unattended.")
    print("                  It fills in the answer; the prompt is still shown.")
    print("                  Confirmations live in: push, deploy, skill remove.")
    print("                  reset ignores it on purpose: deleting every config")
    print("                  file always has to be confirmed by a person.")
    print("                  A command that stops for want of a confirmation")
    print("                  exits non-zero; having nothing to do exits zero.")
    print()
    print(f"{BOLD}Commands:{NC}")
    print("  setup           Configure data repository and verify push access")
    print("                  --account <name> bind a gh account (private HTTPS repos)")
    print("                  --data-dir <path> where the data repository lives")
    print("                  --repo-url <url> clone from, or point the remote at, this")
    print("                  --remote-name <name> git remote to use (default origin)")
    print("                  --replace-remote overwrite a different existing remote")
    print("                  --provider git|gdrive sync transport (default git)")
    print("                  --gdrive-folder <path> Drive folder, nested like A/B")
    print("                  --gdrive-space visible|hidden where Drive files live")
    print("  init [tool]     Gather configs from tool homes into the data repository")
    print("  apply [tool]    Deploy data repository configs to tool home directories")
    print("                  --category settings|skills|all (default all)")
    print("  project [tool]  Project ~/.claude/ directly to other tool home dirs")
    print("  status [tool]   Show diff between the data repository and live configs")
    print("  pull [tool]     Safely fast-forward repo changes, then show status")
    print("  push [tool]     Gather, review, commit, and push local configuration")
    print("                  --allow-secrets skip the credential-content check")
    print("  sync [tool]     Alias for pull")
    print("  list            List managed tools")
    print("  package [skill] Zip a shared skill for Claude Desktop upload")
    print("  reset           Delete all managed config files")
    print("  deploy [dir]    Install chosen skills/plugins/rules into one project only")
    print("                  --profile <name> reuse a saved selection")
    print("                  --save-as <name> remember this selection")
    print("                  --remove  take back what deploy put in (unchanged files only)")
    print("  share <skill>   Copy a Claude skill (or plugin skill) into claude/shared/")
    print("                  --to <both|codex|agy> pick the target tools (default both)")
    print("  unshare <skill> Remove a skill from claude/shared/ (undoes share)")
    print("  ignore-skills [tool]")
    print("                  Stop reporting the tool's own bundled skills")
    print("                  --from <both|codex|agy> limit to one target")
    print("  config          Show provider (git/gdrive), repo, and login state")
    print("  login [account] Bind a GitHub account that can push to the data repo")
    print("                  --unbind drop the binding (gh's own account is never switched)")
    print("  versions        list installed versions; update <ver> switches back")
    print("  hooks <list|enable <name>|disable <name>>")
    print("                  machine-local Claude Code hooks; never synced")
    print("  keepalive <status|enable [HH:MM ...]|disable|send> [claude|codex|agy]")
    print("                  call a tool at chosen times so its five-hour usage")
    print("                  window starts where the day needs it; per machine,")
    print("                  and each tool keeps its own times (default: claude)")
    print("  msg list | setup | send <名稱、id 或 pid> <訊息> [--wait [秒]] [--from <名稱>]")
    print("                  talk to another live Claude/Codex session by name;")
    print("                  setup writes the Claude channel config and prints the")
    print("                  shell function that lets plain `claude` receive")
    print("  memory <status|enable|disable|adopt|release|path|push|autopush>")
    print("                  adopt [專案路徑|all|--scan [目錄]] sync one project's")
    print("                    or find every unsynced one below a directory")
    print("                  enable|disable codex|agy  remember capture on that host only")
    print("                  Shared notebook that every AI tool reads and writes")
    print("                  path --global|--project print one of the two roots")
    print("                  push --if-stale <小時> only when nothing pushed since")
    print("                  autopush status|enable [時]|disable  schedule a daily save")
    print("                  handoff list [專案路徑]|write <線> <內容>|claim [線]|done <線>")
    print("                    hand one work thread to the session that follows")
    print("                  handoff remind status|enable [百分比]|disable")
    print("                    Claude context reminder; memory enable turns it on at 70%")
    print("                  push --allow-secrets skip the credential-content check")
    print("  desktop         Launch the desktop app (bundled on Windows)")
    print("                  --shortcut add desktop and app-menu shortcuts (Windows, Linux)")
    print("                  --wait stay in the foreground (shows errors)")
    print("  gui             Alias for desktop")
    print("  skill           Print the acg usage guide (written for AI agents)")
    print("  skill guide     Alias for the guide; works before setup")
    print("  skill add <dir> Install a local skill into the repo and Claude home")
    print("                  Refuses overwrite; apply --category skills for Codex/agy")
    print("  skill remove <name>")
    print("                  Confirm removal of all standalone sources and mirrors")
    print("                  Includes legacy stores; --force accepts confirmation")
    print("                  For shared copies only, use unshare then apply")
    print("  completion      Print Bash or PowerShell completion script")
    print("  update [version] Install the latest release, or a specific version,")
    print("                  and bring the Claude Code plugin along")
    print("  version         Show the installed version")
    print("  help            Show this help")
    print()
    print(f"{BOLD}Claude Code plugin:{NC}")
    print("  The first install and every update put the /acg skill into Claude")
    print("  Code (AI_CONFIG_NO_PLUGIN=1 skips it). Pick /acg:<subcommand> from")
    print("  the / menu, or type /acg <subcommand>.")
    print("  By hand: claude plugin marketplace add CSL426/ai-config")
    print("           claude plugin install acg@acg")
    print("  status sync save share memory keepalive msg handoff handoffs pickup")
    print()
    print(f"{BOLD}Tools:{NC}")
    print("  claude          Claude Code (~/.claude/)")
    print("  codex           Codex CLI (~/.codex/)")
    print("  agy             Antigravity CLI (~/.gemini/antigravity-cli/)")
    print("  all             All supported tools (default)")


def main(argv: "list[str] | None" = None) -> int:
    return cli_dispatch.main(argv, usage)


if __name__ == "__main__":
    sys.exit(main())
